apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fpultera/argocd-apps.git'
    path: apps/argo-workflows/install/.
    targetRevision: main 
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true