apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# base Argo CD components
- install.yaml

components:
# extensions controller component
- https://github.com/argoproj-labs/argocd-extensions/manifests
