apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: postgresql
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.6.21
    chart: postgresql
    helm:
      values: |
        auth:
          enablePostgresUser: true
          username: "airbyte"
          database: "db-airbyte"
          password: "caca123"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true