apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/fpultera/prometheus-chart'
    targetRevision: main
    path: 'prometheus'
    helm:
      valueFiles:
        - 'env/local/values-serverFiles-prometheus.yaml'
        - 'env/local/values-serverFiles-alerting_rules.yaml'
        - 'env/local/values-alertmanagerFiles-alertmanager.yaml'
        - 'env/local/values-serverFiles-alerting_rules_data.yaml'
        - 'env/local/values.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true