apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-prometheus
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/fpultera/prometheus-chart.git
      revision: HEAD
      files:
      - path: "prometheus/env/teams/config*.json"
  template:
    metadata:
      name: 'prometheus-{{ cluster }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/fpultera/prometheus-chart'
        targetRevision: HEAD
        path: prometheus
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - 'env/{{ cluster }}/values-serverFiles-prometheus.yaml'
            - 'env/{{ cluster }}/values-serverFiles-alerting_rules.yaml'
            - 'env/{{ cluster }}/values-alertmanagerFiles-alertmanager.yaml'
            - 'env/{{ cluster }}/values.yaml'
            - 'env/{{ cluster }}/teams/{{ teams.owner }}/alerting_rules_{{ teams.tl }}.yaml'
      destination:
        server: '{{url}}'
        namespace: prometheus-{{ env }}
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true