apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/fpultera/prometheus-chart'
    targetRevision: main
    path: 'prometheus'
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - 'env/local/values-serverFiles-prometheus.yaml'
        - 'env/local/values-serverFiles-alerting_rules.yaml'
        - 'env/local/values-alertmanagerFiles-alertmanager.yaml'
        - 'env/local/values-serverFiles-alerting_rules_test.yaml'
        - 'env/local/values.yaml'
  # sources:
  #   - repoURL: https://github.com/fpultera/externalValueFiles.git
  #     targetRevision: main
  #     helm:
  #       valueFiles:
  #         - values-serverFiles-alerting_rules_test.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true