apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        env: 'local'
        url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: 'prometheus-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/fpultera/prometheus-chart'
        targetRevision: HEAD
        path: prometheus
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - 'env/{{ cluster }}/values-serverFiles-prometheus.yaml'
            - 'env/{{ cluster }}/values-serverFiles-alerting_rules.yaml'
            - 'env/{{ cluster }}/values-alertmanagerFiles-alertmanager.yaml'
            - 'env/{{ cluster }}/values.yaml'
            - 'teams/data/alerting_rules_data.yaml'
            - 'teams/risk/alerting_rules_risk.yaml'
            - 'teams/wallet/alerting_rules_wallet.yaml'
      destination:
        server: '{{url}}'
        namespace: prometheus-{{ env }}
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true