apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  destination:
    namespace: prometheus-operator-crds
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 0.1.1
    chart: prometheus-operator-crds
    # helm:
    #   values: |
    #     adminui:
    #       service:
    #         type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true