apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqlbee
  namespace: argocd
spec:
  destination:
    namespace: sqlbee
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/connctd/sqlbee'
    targetRevision: master
    path: 'deployment'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true