apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-operator
  namespace: argocd
spec:
  destination:
    namespace: stackgres
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/'
    targetRevision: 1.4.0-RC2
    chart: stackgres-operator
    helm:
      values: |
        adminui:
          service:
            type: ClusterIP
        deploy:
          operator: true
          restapi: true
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true