apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-operator
  namespace: argocd
spec:
  destination:
    namespace: stackgres-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/'
    targetRevision: 1.4.0-RC1
    chart: stackgres-operator
    helm:
      values: |
        adminui:
          name: stackgres-adminui
          image:
            name: "stackgres/admin-ui"
            tag: "main"
            pullPolicy: "IfNotPresent"
          resources: {}
          service:
            exposeHTTP: true
            type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
