apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-operator
  namespace: argocd
spec:
  destination:
    namespace: stackgres
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/'
    targetRevision: latest
    chart: stackgres-operator
    helm:
      values: |
        adminui:
          service:
            type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true